name: HexReplacer
description: For Intel HEX files, the specified byte from the specified address is replaced by the specified data.
version: 1.2.0
environment:
  sdk: 3.6.1
dependencies:
  yaml: ^3.1.3
  csv: ^6.0.0
